### ISSUE TITLE
Message when done installing

### ISSUE THREAD

**Issue by JJK96** [andreyorst/plug.kak#36]
Currently when installing, I see a print: "Installing plugins in background". However I get no message when it is done installing. 

So, currently I do not know when it is done.

**Comment by andreyorst** [comment]
Yeah. I know. This was intentional, since I can't detect when all processes actually finished, because everything is happening asynchronously. I'm thinking about a way how to delay a message without blocking kakoune. 

I will eventually implement fifo buffet which will show progress, rightnow all info is shown in debug buffer

**Comment by andreyorst** [comment]
The problem is that I can't measure parallel functions that are started by kakoune. [Here's issue](https://github.com/mawww/kakoune/issues/2682) where I explain the problem a bit, and there's a proposed solution that advices to use file check, but I've tried multiple ways and can't make it this way, because measuring via variable isn't reliable, and shell does what it want's to do no matter what checks I try to use.

**Comment by andreyorst** [comment]
I guess I'll implement it with `*plug*` buffer, where all info will be shown. Much like in vim-plug

**Comment by andreyorst** [comment]
@JJK96 I've implemented it in FIFO buffer like so:
![vaiv](https://user-images.githubusercontent.com/19470159/51083992-08823500-1734-11e9-945f-3433042327d6.gif)
you can check it time to time to see if everything is done. Unfortunately there's no global message that installation is finished, but you can see that plugin installation state. What do you think?

**Comment by andreyorst** [comment]
Changes are now in kakoune-git branch.

**Comment by JJK96** [comment]
This looks very good! It's a better solution than using the debug buffer. And nice use of coloring.
