### ISSUE TITLE
Local changes to color themes are not copied over

### ISSUE THREAD

**Issue by dgmulf** [andreyorst/plug.kak#65]
When I commit changes to a color theme repo in `$XDG_CONFIG_HOME/kak/plugins`, plug.kak identifies these changes with `plug-list`, but there doesn't seem to be a way of automatically replacing the `.kak` files in `$XDG_CONFIG_HOME/kak/colors`.

**Comment by andreyorst** [comment]
Yes, since post update hooks run on successful update.

I don't want to install color-schemes with symbolic links, because in case plugin, that provides color-scheme is deleted we will have broken links.

What do you think if I add `plug-update-theme-files` command?

**Comment by dgmulf** [comment]
A separate command would be fine, but it would be nice to manage automatically somehow. I was confused at first by the different behavior between normal plugins and color themes. `plug-clean` could remove the symlinks if you went that route.

**Comment by andreyorst** [comment]
removing links with `plug-clean` is a pain point, since we need to understand relations of the links to the plugin we currently cleaning. It's hard. Dangling links is also a thing I'd like to avoid.

> I was confused at first by the different behavior between normal plugins and color themes

this is because plugins are being loaded (sourced) directly, so local changes to plugins will get loaded too. Themes, on the other hand are not loaded. When you use `colorscheme` command it looks up for available theme files located at specific places: in your `%val{config}/colors` and `%val{runtime}/colors` and provides those file names as completions to that command. Unfortunately we cant extend the list of places where to look for themes, so `colorscheme` could find themes installed by plug.kak. If we could though, we will not need to copy theme files to `%val{config}/themes`. There was a feature request for this somewhere at Kakoune, and I'm not sure why it wasn't done in the same way how we can extend the `%opt{path}` option. With this change the theme maintenance process will be pme much much easier for plugins.

Another approach for a theme would be to implement a command, and add it to list of theme commands, that will be used as completions for `colorscheme`, and it will simply call a command that will set the colors. This way we well not even need to distinguish themes and plugins, since there's no difference anymore, and we will not need the `%val{config}/colors` and `%val{runtime}/colors` at all, and it will make plugin manager simpler a lot.
