### ISSUE TITLE
Feature request: add an option to plug-update to make it synchronous

### ISSUE THREAD

**Issue by dead10ck** [andreyorst/plug.kak#82]
I'd like to set up automated updates for my kakoune plugins, and I do this for all my other apps, such as vim, by running a script. For vim, I can just do `vim +PlugUpdate +qa`, and it works, but if I do something similar with plug.kak like `kak -e 'plug-update; quit'`, it simply quits right away before it does any updating.

I am unsure what the cause is, but I can only assume it is because the actual update process is asynchronous and happens in the background, while the user is free to do whatever else in kakoune while the update process is going. While this may be desirable in an interactive setting, it makes it impossible to do updates in an automated way.

**Comment by andreyorst** [comment]
Right now plug.kak is fully asyncronous, and making it synchronous may prove to be a bit difficult, because rightnow the code simply creates subshels in the background. There's no logic whether not to put it to background, because I'm not sure if it is possible to do in shellscript.

We could workaround it by adding a user hook `plug_after_update` or something like that, and you could call `quit` on it for example. Not sure how feasible this is really.

**Comment by dead10ck** [comment]
I mean.. sorry if this sounds a bit dismissive, because I may be speaking from ignorance here, but you can make any asynchronous system synchronous by simply waiting on the task immediately. Right? In bash this would be the `wait` built-in.

**Comment by andreyorst** [comment]
yes, this is possible and the code inside plug_update function spawns
several parallel processes, and implements simple thread pool using `wait`
function. The problem here is that the call to plug_update itself happens
asynchronously as well. I can make optional wait after it but it will not
make whole ptocess completely synchronous, e.g plugins will still update in
parallel, but UI will be blocked as you suggest. If this is acceptable, we
can go this route.

вт, 25 мая 2021 г., 23:50 Skyler Hawthorne ***@***.***>:

**Comment by dead10ck** [comment]
Oh, sorry, I did not make this very clear, but yes, it would actually be desirable for updates to happen in parallel still, but the prompt simply does not exit until all the updates are done. This way doing `kak -e 'plug-update; quit'` will wait for the update to finish before running `quit`. This is what happens with the vim example I mentioned.

**Comment by andreyorst** [comment]
Should be fixed now. See if it works for you. New variable is named `plug_block_ui`

**Comment by dead10ck** [comment]
Thanks @andreyorst! Really appreciated. So far it seems to work great!
